services:
  php:
    build:
      context: .
      target: frankenphp_prod  # 2 espaces d'indentation
    env_file:
      - .env.local  # Liste avec tiret
    environment:
      APP_SECRET: ${APP_SECRET:-}  # Fallback vide si non définie
      # Autres variables si nécessaires
